/*
 * This source file was generated by the Gradle 'init' task
 */
package org

class MainTest {
  // @Test
  // fun appHasAGreeting() {
  //     val classUnderTest = Main()
  //     assertNotNull(classUnderTest.greeting, "app should have a greeting")
  // }
}
