/*
 * This source file was generated by the Gradle 'init' task
 */
package org

import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.assertNotNull

class MainTest {
    // @Test
    // fun appHasAGreeting() {
    //     val classUnderTest = Main()
    //     assertNotNull(classUnderTest.greeting, "app should have a greeting")
    // }
}

